print('pytanie: Jak masz na imię oraz nazwisko?')
input('odpowiedź: ')
print('pytanie: Najczęstszym sposobem spędzania wolnego czasu jest dla Ciebie?')
input('odpowiedź: ')
print('pytanie: W jakich okolicznościach czytasz książki najczęściej??')
input('odpowiedź: ')
print('pytanie: Jeżeli spędzasz czas wolny czytając książki, jaki jest główny powód takiego wyboru?')
input('odpowiedź: ')
print('pytanie: Po książki w jakiej formie sięgasz najczęściej?')
input('odpowiedź: ')
print('pytanie: Ile książek czytasz średnio w ciągu roku?')
input('odpowiedź: ')
print('pytanie: Jak często średnio czytasz książki?')
input('odpowiedź: ')
print('pytanie: Po jakie gatunki książek sięgasz najczęściej?')
input('odpowiedź: ')